---
include:
  - board: nice_nano_v2 
    shield: temper_left nice_view_adapter nice_epaper
  - board: nice_nano_v2
    shield: temper_right nice_view_adapter nice_epaper
  - board: nice_nano_v2 
    shield: settings_reset
