---
include:
  - board: nice_nano
    shield: temper_left nice_view_adapter nice_epaper
  - board: nice_nano
    shield: temper_right nice_view_adapter nice_epaper
  - board: nice_nano
    shield: settings_reset
